[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=-crt-static"]
linker = "x86_64-unknown-linux-gnu-gcc"

[target.x86_64-apple-darwin]
rustflags = ["-C", "target-feature=-crt-static"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-feature=-crt-static"]