name: ps3dec building
on:
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-gnu
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: macos-latest
            target: x86_64-apple-darwin
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true
    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y musl-tools build-essential gcc
    - name: Set up musl-gcc linker
      if: matrix.os == 'ubuntu-latest'
      run: |
        echo "[target.x86_64-unknown-linux-musl]" >> ~/.cargo/config
        echo "linker = \"musl-gcc\"" >> ~/.cargo/config
    - name: Build
      run: |
        rustc -vV
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          export CC_x86_64_unknown_linux_musl=musl-gcc
          cargo build --verbose --release --target x86_64-unknown-linux-musl
        else
          cargo build --verbose --release --target ${{ matrix.target }}
        fi
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ps3decremake_cli-${{ matrix.target }}
        path: |
          target/${{ matrix.target }}/release/ps3decremake_cli*
          target/${{ matrix.target }}/release/libps3decremake.*
        if-no-files-found: error
